services:
  microtasks:
    container_name: microtasks
    restart: always
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - /data/microtasks:/data
    environment:
      - CLICKHOUSE_HOST=http://172.17.0.1:8123
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=ru-central1
      - AWS_ENDPOINT_URL=https://storage.yandexcloud.net
      - AWS_BUCKET=static.wotstat.info
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      bridge:
        ipv4_address: 172.29.0.10

networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
