services:
  microtasks:
    container_name: microtasks
    build:
      dockerfile: Dockerfile.dev
    environment:
      - CLICKHOUSE_HOST=http://db.wotstat.info:80
    volumes:
      - ./dev-data:/data
