-- Schema reference only; do not execute against existing tables.

CREATE TABLE WOT.Comp7Leaderboard (`region` LowCardinality(String), `recalculationTime` DateTime, `name` String, `bdid` UInt64, `clan` LowCardinality(String), `clanColor` UInt32, `rank` UInt32, `rating` UInt16, `battlesCount` UInt16, `elite` Bool, `day` Date MATERIALIZED toStartOfDay(recalculationTime + toIntervalHour(transform(region, ['RU', 'EU', 'ASIA', 'NA', 'CN'], [-3, -9, -8, -20, -4], 0)))) ENGINE = ReplacingMergeTree ORDER BY (region, bdid, recalculationTime) SETTINGS index_granularity = 8192;

CREATE TABLE WOT.Comp7LeaderboardByRank (`region` LowCardinality(String), `recalculationTime` DateTime, `name` String, `bdid` UInt64, `clan` LowCardinality(String), `clanColor` UInt16, `rank` UInt32, `rating` UInt16, `battlesCount` UInt16, `elite` Bool, `day` Date) ENGINE = ReplacingMergeTree ORDER BY (region, recalculationTime, rank) SETTINGS index_granularity = 8192;

CREATE TABLE WOT.Comp7LeaderboardDaily (`region` LowCardinality(String), `day` Date, `bdid` UInt64, `lastRecalculationTime` SimpleAggregateFunction(max, DateTime), `lastSnapshot` AggregateFunction(argMax, Tuple(name String, clan String, clanColor UInt32, rank UInt32, rating UInt16, battlesCount UInt16, elite UInt8), DateTime), `firstSnapshot` AggregateFunction(argMin, Tuple(rank UInt32, rating UInt16, battlesCount UInt16, elite UInt8), DateTime), `minRank` SimpleAggregateFunction(min, UInt32), `maxRank` SimpleAggregateFunction(max, UInt32), `minRating` SimpleAggregateFunction(min, UInt16), `maxRating` SimpleAggregateFunction(max, UInt16), `minElite` SimpleAggregateFunction(min, UInt16), `maxElite` SimpleAggregateFunction(max, UInt16)) ENGINE = AggregatingMergeTree ORDER BY (region, day, bdid) SETTINGS index_granularity = 8192;

CREATE TABLE WOT.Comp7LeaderboardDailyByRank (`region` LowCardinality(String), `day` Date, `lastRank` UInt32, `lastDayRank` UInt32, `lastRecalculationTime` DateTime, `bdid` UInt64, `name` String, `clan` String, `clanColor` UInt32, `minRank` UInt32, `maxRank` UInt32, `firstRank` UInt32, `minRating` UInt16, `maxRating` UInt16, `firstRating` UInt16, `lastRating` UInt16, `lastDayRating` UInt16, `firstBattlesCount` UInt16, `lastBattlesCount` UInt16, `lastDayBattlesCount` UInt16, `minElite` UInt8, `maxElite` UInt8, `firstElite` UInt8, `lastElite` UInt8, `lastDayElite` UInt8) ENGINE = ReplacingMergeTree(lastRecalculationTime) PARTITION BY toYYYYMM(day) ORDER BY (region, day, lastRank) SETTINGS index_granularity = 8192;

CREATE MATERIALIZED VIEW WOT.comp7_leaderboard_by_rank_mv TO WOT.Comp7LeaderboardByRank (`region` LowCardinality(String), `recalculationTime` DateTime, `name` String, `bdid` UInt64, `clan` LowCardinality(String), `clanColor` UInt32, `rank` UInt32, `rating` UInt16, `battlesCount` UInt16, `elite` Bool, `day` Date) AS SELECT *, day FROM WOT.Comp7Leaderboard;

CREATE MATERIALIZED VIEW WOT.comp7_leaderboard_daily_by_rank_rmv REFRESH EVERY 5 MINUTE APPEND TO WOT.Comp7LeaderboardDailyByRank (`region` LowCardinality(String), `day` Date, `lastRank` UInt32, `lastDayRank` UInt32, `lastRecalculationTime` SimpleAggregateFunction(max, DateTime), `bdid` UInt64, `name` String, `clan` String, `clanColor` UInt32, `minRank` SimpleAggregateFunction(min, UInt32), `maxRank` SimpleAggregateFunction(max, UInt32), `firstRank` UInt32, `minRating` SimpleAggregateFunction(min, UInt16), `maxRating` SimpleAggregateFunction(max, UInt16), `firstRating` UInt16, `lastRating` UInt16, `lastDayRating` UInt16, `firstBattlesCount` UInt16, `lastBattlesCount` UInt16, `lastDayBattlesCount` UInt16, `minElite` SimpleAggregateFunction(min, UInt16), `maxElite` SimpleAggregateFunction(max, UInt16), `firstElite` UInt8, `lastElite` UInt8, `lastDayElite` UInt8) DEFINER = default SQL SECURITY DEFINER AS WITH todayData AS (WITH argMaxMerge(lastSnapshot) AS last, argMinMerge(firstSnapshot) AS first SELECT region, day, last.rank AS lastRank, max(lastRecalculationTime) AS lastRecalculationTime, bdid, last.name AS name, last.clan AS clan, last.clanColor AS clanColor, min(minRank) AS minRank, max(maxRank) AS maxRank, first.rank AS firstRank, min(minRating) AS minRating, max(maxRating) AS maxRating, first.rating AS firstRating, last.rating AS lastRating, first.battlesCount AS firstBattlesCount, last.battlesCount AS lastBattlesCount, min(minElite) AS minElite, max(maxElite) AS maxElite, first.elite AS firstElite, last.elite AS lastElite FROM WOT.Comp7LeaderboardDaily WHERE day >= (today() - 1) GROUP BY region, day, bdid HAVING lastRecalculationTime >= (now() - toIntervalMinute(6)) QUALIFY lastRecalculationTime = max(lastRecalculationTime) OVER (PARTITION BY region)), lastDayData AS (WITH argMaxMerge(lastSnapshot) AS last SELECT region, day, bdid, last.rank AS rank, last.battlesCount AS battlesCount, last.rating AS rating, rating, last.elite AS elite FROM WOT.Comp7LeaderboardDaily WHERE day = (SELECT any(day) - 1 FROM todayData) GROUP BY region, day, bdid) SELECT region, day, lastRank, lastDayData.rank AS lastDayRank, lastRecalculationTime, bdid, name, clan, clanColor, minRank, maxRank, firstRank, minRating, maxRating, firstRating, lastRating, lastDayData.rating AS lastDayRating, firstBattlesCount, lastBattlesCount, lastDayData.battlesCount AS lastDayBattlesCount, minElite, maxElite, firstElite, lastElite, lastDayData.elite AS lastDayElite FROM todayData LEFT JOIN lastDayData USING (region, bdid) ORDER BY lastRank ASC;

CREATE MATERIALIZED VIEW WOT.comp7_leaderboard_daily_mv TO WOT.Comp7LeaderboardDaily (`region` LowCardinality(String), `day` Date, `bdid` UInt64, `lastRecalculationTime` SimpleAggregateFunction(max, DateTime), `lastSnapshot` AggregateFunction(argMax, Tuple(name String, clan String, clanColor UInt32, rank UInt32, rating UInt16, battlesCount UInt16, elite UInt8), DateTime), `firstSnapshot` AggregateFunction(argMin, Tuple(rank UInt32, rating UInt16, battlesCount UInt16, elite UInt8), DateTime), `minRank` SimpleAggregateFunction(min, UInt32), `maxRank` SimpleAggregateFunction(max, UInt32), `minRating` SimpleAggregateFunction(min, UInt16), `maxRating` SimpleAggregateFunction(max, UInt16), `minElite` SimpleAggregateFunction(min, Bool), `maxElite` SimpleAggregateFunction(max, Bool)) AS SELECT region, day, bdid, maxSimpleState(recalculationTime) AS lastRecalculationTime, argMaxState(CAST((name, clan, clanColor, rank, rating, battlesCount, elite), 'Tuple(\n                           name String,\n                           clan String,\n                           clanColor UInt32,\n                           rank UInt32,\n                           rating UInt16,\n                           battlesCount UInt16,\n                           elite UInt8\n                       )'), recalculationTime) AS lastSnapshot, argMinState(CAST((rank, rating, battlesCount, elite), 'Tuple(\n                           rank UInt32,\n                           rating UInt16,\n                           battlesCount UInt16,\n                           elite UInt8\n                       )'), recalculationTime) AS firstSnapshot, minSimpleState(rank) AS minRank, maxSimpleState(rank) AS maxRank, minSimpleState(rating) AS minRating, maxSimpleState(rating) AS maxRating, minSimpleState(elite) AS minElite, maxSimpleState(elite) AS maxElite FROM WOT.Comp7Leaderboard GROUP BY region, day, bdid;